sudo: required
services:
- docker
env:
  global:
  - PI_APP=alexa-youtube
script:
- ls
- ls $TRAVIS_BUILD_DIR
- ls $TRAVIS_BUILD_DIR/alexasecrets
- docker run  -v $TRAVIS_BUILD_DIR/code:/code -v $TRAVIS_BUILD_DIR/alexasecrets:/root migruiz/alexa-cli 
notifications:
  email:
  - mig.ruiz@gmail.com
before_install:
- openssl aes-256-cbc -K $encrypted_83630750896a_key -iv $encrypted_83630750896a_iv
  -in alexasecrets.tar.enc -out alexasecrets.tar -d
- tar xvf alexasecrets.tar
