sudo: required
services:
- docker
env:
  global:
  - PI_APP=alexa-youtube
script:
- docker run --rm                                   -v $TRAVIS_BUILD_DIR/code:/code -v $TRAVIS_BUILD_DIR/alexasecrets/.ask:/root/.ask -v $TRAVIS_BUILD_DIR/alexasecrets/.aws:/root/.aws migruiz/alexa-cli deploy -t skill
- docker run --rm                                   -v $TRAVIS_BUILD_DIR/code:/code -v $TRAVIS_BUILD_DIR/alexasecrets/.ask:/root/.ask -v $TRAVIS_BUILD_DIR/alexasecrets/.aws:/root/.aws migruiz/alexa-cli deploy -t model
- docker run --rm  --entrypoint "/uploadlambda.sh"  -v $TRAVIS_BUILD_DIR/code:/code -v $TRAVIS_BUILD_DIR/alexasecrets/.ask:/root/.ask -v $TRAVIS_BUILD_DIR/alexasecrets/.aws:/root/.aws migruiz/alexa-cli alexa-youtube
notifications:
  email:
  - mig.ruiz@gmail.com
before_install:
- openssl aes-256-cbc -K $encrypted_83630750896a_key -iv $encrypted_83630750896a_iv
  -in alexasecrets.tar.enc -out alexasecrets.tar -d
- tar xvf alexasecrets.tar
