sudo: required
services:
- docker
env:
  global:
  - PI_APP=alexa-youtube
script:
- docker run --rm -v code:/code -v alexasecrets:/root migruiz/alexa-cli deploy
notifications:
  email:
  - mig.ruiz@gmail.com
before_install:
- openssl aes-256-cbc -K $encrypted_83630750896a_key -iv $encrypted_83630750896a_iv
  -in alexasecrets.tar.enc -out alexasecrets.tar -d
